### PR TITLE
Patch subquery with json column access

### LINKED ISSUE #187: Support for Subquery during Transpilation
Description: During transpiliation, an error is raised whenever there is a subquery

Exception: 'Expected table name but got <Token token_type: TokenType.L_PAREN, text: (
Error: ParserError(file_name='/Workspace/Users/XXX/tools/sf_tasks/XX.sql', exception=ParseError("Expected table name but got <Token token_type: TokenType.L_PAREN, text: (, line: 116, col: 6, start: 5440, end: 5440, comments: []>
Expected output: Transpiler should transpile subquery as well

### PR DESCRIPTION
**Pull request by sundarshankar89**
fixes #187

### CODE REVIEW

**Review by nfx — APPROVED** [review]
lgtm

**Comment by sundarshankar89** [comment]
@nfx  merging the code, will fix forward the pylint disable errors as this PR didn't introduce this change.

**Review by vijaypavann-db — APPROVED** [review]
LGTM
Koantek - reported newer version of transpiler tool is working better. No longer have blockers

**Review by nfx — APPROVED** [review]
Lgtm

**Pull request merged**
