### PR TITLE
Update `Row` attribute 

### LINKED ISSUE #306: [BUG]: Validation is throwing weird error
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of Bug / Issue

ValidationError

### Current Behavior

Command: ` databricks labs remorph transpile --input-sql /Users/ganesh.dogiparthi/DB/Dropbox/Hive/hive1.sql --source presto --debug --profile default --skip-validation false --catalog-name data --schema-name testing`

Query used for transpiling and validation: `select id_no as id, char_name as name, sal * 2 as sal, coalesce(comm,0) as comm from data.testing.friends;`

image

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Relevant log output or Exception details

_No response_

### Sample Query

_No response_

### Operating System

macOS

### Version

latest via Databricks CLI

### PR DESCRIPTION
**Pull request by vijaypavann-db**
closes #306 

`pyspark.sql.Row` has only [asDict](https://spark.apache.org/docs/3.1.3/api/python/reference/api/pyspark.sql.Row.asDict.html#pyspark.sql.Row.asDict
) attribute.

Updated `as_dict` to `asDict`

### CODE REVIEW

**Comment by vijaypavann-db** [comment]
Have to fix the following Testcases by updating `MockBackend`: 

*  FAILED tests/unit/helpers/test_validation.py::test_valid_query - AttributeError: asDict. Did you mean: 'as_dict'?
*  FAILED tests/unit/helpers/test_validation.py::test_validate_format_result_with_valid_query - AttributeError: asDict. Did you mean: 'as_dict'?
*  FAILED tests/unit/helpers/test_validation.py::test_validate_format_result_with_invalid_query - AttributeError: asDict. Did you mean: 'as_dict'?

**Comment by sundarshankar89** [comment]
@bishwajit-db can you make a PR in LSQL to accommodate these changes in `mockbackend`

**Comment by sundarshankar89** [comment]
@vijaypavann-db lsql is released please check

**Comment by ganeshdogiparthi-db** [comment]
FAILED tests/unit/helpers/test_validation.py::test_valid_query - AttributeError: asDict. Did you mean: 'as_dict'?
FAILED tests/unit/helpers/test_validation.py::test_validate_format_result_with_valid_query - AttributeError: asDict. Did you mean: 'as_dict'?
FAILED tests/unit/helpers/test_validation.py::test_validate_format_result_with_invalid_query - AttributeError: asDict. Did you mean: 'as_dict'?


@vijaypavann-db and @bishwajit-db These are still failing.

**Review by sundarshankar89 — APPROVED** [review]
LGTM

**Comment by derekyidd** [comment]
Thanks for this!

@sundarshankar89 when will 0.1.8 release come with this change?

**Comment by sundarshankar89** [comment]
@derekyidd we will do release containing this fix next week

**Comment by derekyidd** [comment]
@sundarshankar89 bump on when the next release will come!

**Comment by sundarshankar89** [comment]
@derekyidd  release is out today.

**Pull request merged**
