### PR TITLE
Snowflake driver and user transformation to partition & join col

### PR DESCRIPTION
**Pull request by ganeshdogiparthi-db**
* Reverted the code to apply only user transformations to key cols and join cols in `Hash query` and `Threshold source query`
* In the compare class we use `null safe equality join` for `hash comparison`.
* Created a map entry for snowflake driver in `jdbc_reader.py`

### CODE REVIEW

**Review by sundarshankar89 — APPROVED** [review]
LGTM

**Comment by vijaypavann-db** [comment]
Is `SnowflakeDriver`: `net.snowflake.client.jdbc.SnowflakeDriver`  available on all clusters by default, or do we need to install something similar to the `ojdbc8` jar?

**Comment by ganeshdogiparthi-db** [comment]
@vijaypavann-db 
It is available already in our cluster. I have never installed it manually.

**Comment by ganeshdogiparthi-db** [comment]
@sundarshankar89  Can we close this please?

**Review by vijaypavann-db — APPROVED** [review]
LGTM

**Pull request merged**
