### PR TITLE
Add core contribution guidelines

### PR DESCRIPTION
**Pull request by vil1**

### CODE REVIEW

**Review by sundarshankar89 — APPROVED** [review]

**Comment by sundarshankar89** [comment]
@nfx you how are you managing unsigned commits? I don't have access to force merge.

**Comment by vil1** [comment]
I cannot come up with an example query for covering the 
```scala
else {
  ir.UnspecifiedJoin
}
``` 
lines codecov is (legitimately) complaining about. To the extent of my (limited) current knowledge, this branch should never get evaluated (but it has to be there for the code to compile). Should I throw an exception instead of returning `ir.UnspecifiedJoin`? Would that be enough for codecov to ignore the fact that this line isn't covered by any test? If not, what should I do?

**Comment by nfx** [comment]
@sundarshankar89 all commits are squashed once they're merged to `main` and signed, so we should be fine.

**Review by nfx — APPROVED** [review]
lgtm

**Comment by nfx** [comment]
@sundarshankar89 
image

**Pull request merged**
