### PR TITLE
General cleanup and housekeeping

### PR DESCRIPTION
**Pull request by jimidle**
Rule names in the grammar used Python style snake_case naming conventions, and have now been changed to use camelCase, with which, ANTLR4 then generates PascalCase and results in our visitor methods and context names conforming to our Scala style guidelines.

Also includes do some small general cleanup of code to follow Scala and Databricks Scala style guidelines. 

Progresses: #275

### CODE REVIEW

**Comment by jimidle** [comment]
Note: Awaiting #308 so I can rebase this on main

**Review by vil1 — CHANGES_REQUESTED** [review]
This seems to include changes from #307 and #308, making it difficult to figure out what's the actual change this PR carries. Please rebase this branch on main (or wait for the previous PRs to be merged before submitting this one again).

**Comment by jimidle** [comment]
As noted in my comment. I am queued 3 prs deep. If the first one is merged
I will rebase and it will resolve. The prs are dependent on each other

**Comment by jimidle** [comment]
Rebased from main - only includes changes for this PR now the other two are closed.

**Comment by jimidle** [comment]
@vil1 - Do you have time for a review please?

**Review by nfx — APPROVED** [review]
lgtm

**Pull request merged**
