### PR TITLE
bug fix for to_array function

### LINKED ISSUE #944: [BUG]: TO_ARRAY function needs 1 argument
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of Bug / Issue

TranspileParserError

### Current Behavior

Transpilation throws exception that TO_ARRAY() function needs 1 argument

### Expected Behavior

should transpile the function correctly

### Steps To Reproduce

1. run transpilation

### Relevant log output or Exception details

```shell
The number of provided arguments (2) is greater than the maximum number of supported arguments (1). Line 58, Col: 66.       TO_ARRAY(IFNULL(email_list_ids, ARRAY_CONSTRUCT(NULL)), 'STRING'--> )
```

### Sample Query

```shell
SELECT
        TO_ARRAY(IFNULL(email_list_ids, ARRAY_CONSTRUCT(NULL)), 'STRING') AS email_list_ids
    FROM SCHEMA.DATABASE.TABLE
```

### Operating System

macOS

### Version

latest via Databricks CLI

### PR DESCRIPTION
**Pull request by aman-db**
closes #944 
TO_ARRAY function expects only one param changed it to expect two params (2nd being optional)

### CODE REVIEW

**Comment by sundarshankar89** [comment]
@aman-db  have you pushed the sqlglot changes?

**Comment by aman-db** [comment]
> @aman-db have you pushed the sqlglot changes?

not yet @sundarshankar89

**Review by sundarshankar89 — APPROVED** [review]
LGTM

**Comment by sundarshankar89** [comment]
nit: Please fix the PR Title

**Review by nfx — APPROVED** [review]
lgtm

**Pull request merged**
