### PR TITLE
Guide user on missing configuration file

### LINKED ISSUE #919: [BUG]: Need help installing Recon
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of Bug / Issue

ReconcileError

### Current Behavior

Hello,

I'm trying to use Recon to validate our CDC pipeline which send data from MariaDB to Databricks with Unity. I have setup a foreign catalog to MariaDB since MySQL is not supported by Recon yet.
I'm now trying to configure Recon to work with this setup, but if fails with an error message not really useful:

databricks -p prod  labs remorph reconcile

Cannot find recon table configuration in existing `reconcile` installation. Please provide the configuration file
Error: exit status 1

My config:

reconcile.yml
```yaml
data_source: databricks
database_config:
  source_schema: sga
  target_catalog: prod_ca_regional
  target_schema: landing
metadata_config:
  catalog: prod_ca_regional
  schema: reconcile
  volume: reconcile_volume
report_type: all
secret_scope: p-cac-b05-dhubreg-kv-kvd
version: 1
```

recon_config_databricks_prod_ca_regional_all.json
```json
{
  "source_catalog": "mariadb_ca",
  "source_schema": "sga",
  "target_catalog": "prod_ca_regional",
  "target_schema": "landing",
  "tables": [...]
}
```

### Expected Behavior

An error message that provides the names of the expected configuration files.

### Steps To Reproduce

_No response_

### Relevant log output or Exception details

_No response_

### Sample Query

_No response_

### Operating System

macOS

### Version

latest via Databricks CLI

### PR DESCRIPTION
**Pull request by ludovicc**
Displays the name of the configuration file requested on error.

Fixes #919

### CODE REVIEW

**Review by vijaypavann-db — APPROVED** [review]
LGTM

**Comment by nfx** [comment]
@ludovicc please reply with `I am signing Databricks CLA on behalf of myself as an individual and no other person or entity, including my employer, has or will have rights with respect my Contributions. https://gist.github.com/smikailli/25902b59426b533154bd985b571dde70` or `I am signing on behalf of my employer or a legal entity and I have the actual authority to contractually bind such entity (the Corporation).`

our automated CLA tracking is currently broken and we need to collect confirmations somehow

**Comment by ludovicc** [comment]
I am signing Databricks CLA on behalf of myself as an individual and no other person or entity, including my employer, has or will have rights with respect my Contributions. https://gist.github.com/smikailli/25902b59426b533154bd985b571dde70

**Comment by nfx** [comment]
Keeping track of https://github.com/databrickslabs/remorph/pull/930#issuecomment-2371220644
image

**Review by nfx — APPROVED** [review]

**Pull request merged**
